### PR TITLE
Add notification when entering quest area

### PR DESCRIPTION
**Pull request by jfrankl**
image

### CODE REVIEW

**Comment by caseypt** [comment]
Added a commit to integrate the confirmation screen.

Testing:

- Move into a zone. The zone confirmation dialog should appear.
- Tap "Dismiss". The dialog should shrink in size.
- Leave the zone. The dialog should disappear.
- Move to another zone. Tap "Enter" on the dialog. The dialog should disappear and the zone should begin.

Connects to #103.

**Comment by caseypt** [comment]
Also, the Nexus tablet has been updated with this branch.

**Comment by lliss** [comment]
Seeing some issues with this on iPad.

img_0063

**Comment by jfrankl** [comment]
Any thoughts @caseypt? I just checked it out on an iPad using developer tools. Looks like no content is being appended to #enterarea.

image

**Comment by caseypt** [comment]
Sorry. I'll investigate.

On Mon, Jul 13, 2015 at 6:03 PM, Jeff Frankl <notifications@github.com>
wrote:

> Any thoughts @caseypt <https://github.com/caseypt>? I just checked it out
> on an iPad using developer tools. Looks like no content is being appended
> to #enterarea.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1809908/8661931/66962e5e-2989-11e5-8e6a-5ba50192f399.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azavea/pwd-waterworks-revealed/pull/118#issuecomment-121075528>
> .
>



-- 
Casey Thomas, Software Developer

Azavea  |  340 N 12th St, Suite 402, Philadelphia, PA
cthomas@azavea.com | T 215.558.6185 | F 215.925.2663
Web azavea.com  |  Blog azavea.com/blogs  |  Twitter @azavea
<https://twitter.com/azavea>

**Comment by caseypt** [comment]
I think I just didn't have the latest rebase push up. Sorry about that. Give it another go when you get a chance.

**Comment by lliss** [comment]
This is a problem with setting min-height to 80vh by default. When the application starts we just have a big empty div sitting in the middle of the screen.

**Comment by caseypt** [comment]
@lliss Are you able to see this anywhere else besides the iPad?

**Comment by lliss** [comment]
Yeah, in safari. Looks like we need the -webkit prefix. I added it and improved the transitions a bit. Take a look.

**Comment by caseypt** [comment]
Thanks @lliss. Changes look good to me. Happy to merge after @jfrankl gets a look.

**Comment by lliss** [comment]
+1 tested on both devices.

**Pull request merged**
