### PR TITLE
Feature/lol/new card instructions

### PR DESCRIPTION
**Pull request by lliss**
Connects #123 

Reworks the interface to match new designs show in #123. Images and better styling are missing and will be supplied by @jfrankl. 
 * Creates a global instruction screen that shows up as first card of first zone entered and never again.
 * Creates an alignment message and different instructions on first card of zone.
 * Starts audio playing only when swiping to second card in zone.

To test:
 * build and run
 * Start app. Enter zone.
 * Regardless of which zone is entered you should see the global instruction page.
 * Subsequent loads of the zone or different zones should not show the instruction page.
 * Loading the audio zone (southmost zone on east side) should play audio only after moving to second card in zone (not counting intro card if you visit here first).
 * Leaving and re-entering the zone should continue to play audio.
 * Paused audio should not start playing again if you move back to the initial alignment screen and then forward. Auto play should only occur one time on each load of a zone and this should happen when moving from the first card (alignment card) to second card.

### CODE REVIEW

**Comment by jfrankl** [comment]
Looks good Laurence. I have two changes I'd like to see:

1. I would like for the transition from the second "Align your screen" page into the first page with the audio to work like the transition from the first "Align your screen" page into the second "Align your screen page": I like the way it fades in rather than slides. I think it would be ideal for the second "Align your screen" page to not be part of the slide show in the same way that the first is not.

2. I would like for the "Swipe left to continue" content to be fixed like the top bar with the X—it shouldn't slide from screen to screen.

**Comment by lliss** [comment]
Ok. I'm moving these request to a new issue since they require further restructuring card mechanism. It we have extra time this sprint we'll try to tackle them. But they may have to wait.

**Comment by lliss** [comment]
Made updates to better deal with audio player.

**Comment by caseypt** [comment]
Should you be able to swipe away the first card (not the global instruction card) instead of tapping next? You currently can do this.

**Comment by lliss** [comment]
I intentionally left that in. I felt that it was cumbersome to not support this. After the user figures out the UI it seemed like we shouldn't be pedantic about how they move from one card to the next. If they want to move back and forth quickly swiping is more natural.

**Comment by caseypt** [comment]
Sounds good. +1. Tested on Android and iOS.

**Pull request merged**
